- name: Create dirs structure
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop: "{{ dirs }}"
  tags: filesystem


  
- name: Create symbolic links git - dotfiles
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop: "{{ links }}"
  tags: links
