# The file defines variables to be called everywhere as:
#  vars_files:
#    - vars/global.yml

user_name: me
user_home: "/home/{{ user_name }}"
hostname_test: "testing"
edifier_mac: "60:F4:3A:4D:43:08"
