- name: Ensure user has passwordless sudo
  copy:
    dest: "/etc/sudoers.d/{{ user_name }}"
    content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  become: true
  tags: passwordless

