- name: Register the host with RHEL
  ansible.builtin.redhat_subscription:
    state: present
    username: "{{ rhel_subscription_username }}"
    password: "{{ rhel_subscription_password }}"
    auto_attach: true
  tags: subscription
