- name: Register the host with RHEL
  ansible.builtin.redhat_subscription:
    state: present
    username: "{{ rhel_subscription_username }}"
    password: "{{ rhel_subscription_password }}"
    auto_attach: true
  become: true
  no_log: true  # This hides the decrypted password from logs/output
