$ANSIBLE_VAULT;1.1;AES256
34383666393036393133346539353861663662356430393066333231353765636363623730303761
3663663939326566363364626562383735353439393231300a373561386135396638386434653161
61323830336236346332386266663531356463656533356561636563356337653361386363633935
3937376132396239660a303536376164393639666632326136386338376262313736393837373331
35333434306235303336376661336333663635363761623139386630333163666663353238653030
35303064353966633132373935323562366466326534623830326364393763383535633662353434
39353562343530613861326430653164343361653830323636386633636366363534393262373561
34313331623836636265656230386537653738633838333561373536636131633763373436313632
34336239306534663863373562633337303038393030316434616234633933633065626431333634
61376465316465386564383033396261316665663133343164643161353466346133656433626337
37313730383936373265333763343735373734306134383235653564636135653462343237636362
63363063343034666364656438393031363739643563623132376131663966363533663664636463
35653638303330646231633931636237346464323238666638363363323330366462
